# -*- coding: utf-8 -*-
"""FACE RECOGNITION

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ImmcjSRCTIrAlkMsgCUxYSVvxglbVC1t
"""

!pip install face-recognition

"""# FACE RECOGNITION"""

#YOU HAVE TO INSTALL ESSENTIAL LIBRABRIES
!pip install face-recognition

#IMPORT ALL ESSENTIAL LIBRARIES
import cv2
import numpy as np
import face_recognition
from google.colab.patches import cv2_imshow

imgElon = face_recognition.load_image_file('WRITE IMAGE PATH')    #LOAD IMAGE
imgElon = cv2.cvtColor(imgElon,cv2.COLOR_BGR2RGB)                 #CONVERT IMAGE BGR TO RGB

imgTest = face_recognition.load_image_file('WRITE IMAGE PATH')    #LOAD IMAGE
imgTest = cv2.cvtColor(imgTest,cv2.COLOR_BGR2RGB)                 #CONVERT IMAGE BGR TO RGB

faceLoc = face_recognition.face_locations(imgElon)[0]
encodeElon = face_recognition.face_encodings(imgElon)[0]
cv2.rectangle(imgElon,(faceLoc[3],faceLoc[0]),(faceLoc[1],faceLoc[2]),(255,0,255),2)
#print(faceLoc)
faceLocTest = face_recognition.face_locations(imgTest)[0]
encodeTest = face_recognition.face_encodings(imgTest)[0]
cv2.rectangle(imgTest,(faceLocTest[3],faceLocTest[0]),(faceLocTest[1],faceLocTest[2]),(255,0,255),2)

results = face_recognition.compare_faces([encodeElon],encodeTest)
faceDis = face_recognition.face_distance([encodeElon],encodeTest)
print(results,faceDis)
cv2.putText(imgElon,f'{results}{round(faceDis[0],2)}',(50,50),cv2.FONT_HERSHEY_COMPLEX,1,(0,0,255),2)

cv2_imshow(imgElon)
cv2_imshow(imgTest)
cv2.waitKey(0)

